language: node_js
node_js:
  - "8.11.1"
services:
  - mongodb
  - redis-server
sudo: false
cache:
  directories:
    - node_modules
before_install:
  # Update Node.js modules
  - "test ! -d node_modules || npm prune"
  - "test ! -d node_modules || npm rebuild"
notifications:
  slack: ohmlabs:5MGtAi5UufagxhoS5Gv5pvPF
