version: "2"
services:
  nginx:
    build:
      context: .
      dockerfile: ohm/docker/nginx/Dockerfile
    links:
      - node:node
    ports:
      - "8080:8080"
  node:
    build: 
      context: .
      dockerfile: ohm/docker/Dockerfile
    links:
      - redis
      - mongo
    ports:
      - "8888"
  mongo:
    image: mongo
    ports:
     - "2701"
  redis:
    image: redis
    ports:
      - "6379"
